# Generated by Django 4.2.30 on 2026-04-15 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('lesson_format', models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person'), ('both', 'Both')], default='online', max_length=10)),
                ('teaching_levels', models.JSONField(default=list)),
                ('age_groups', models.JSONField(blank=True, default=list)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True)),
                ('pricing_info', models.CharField(blank=True, max_length=255)),
                ('profile_photo_url', models.URLField(blank=True)),
                ('intro_audio_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100)),
                ('proficiency_type', models.CharField(choices=[('native', 'Native Speaker'), ('fluent', 'Fluent'), ('professional', 'Professional')], default='native', max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='teachers.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'language_name')},
            },
        ),
    ]
