# Generated by Django 4.2.30 on 2026-07-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
