# Generated by Django 4.2.30 on 2026-07-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_marketplace_data_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='work_experience',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
