# Generated by Django 4.2.30 on 2026-09-29 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0004_teacher_work_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="availability",
            options={
                "verbose_name": "availability slot",
                "verbose_name_plural": "availability",
            },
        ),
    ]
