# Generated by Django 4.2.30 on 2026-07-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
