# Generated by Django 4.2.30 on 2026-07-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_google_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='learner_whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
