# Generated by Django 4.2.30 on 2026-07-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_learner_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='learner_google_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
