# Generated by Django 4.2.30 on 2026-07-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_request', 'Booking Request'), ('booking_confirmed', 'Booking Confirmed'), ('booking_declined', 'Booking Declined'), ('booking_cancelled', 'Booking Cancelled'), ('lesson_reminder', 'Lesson Reminder'), ('welcome', 'Welcome'), ('profile_approved', 'Profile Approved'), ('profile_rejected', 'Profile Rejected'), ('new_message', 'New Message')], max_length=30),
        ),
    ]
