# Generated by Django 4.2.30 on 2026-04-15 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('language_name', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('text', 'Text'), ('pdf', 'PDF'), ('audio', 'Audio'), ('image', 'Image'), ('link', 'Link')], max_length=15)),
                ('file_url', models.URLField(blank=True)),
                ('content_text', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('teacher_only', 'Teacher Only'), ('student_shared', 'Student Shared')], default='teacher_only', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_resources', to='bookings.booking')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_attachments', to='resources.resource')),
            ],
            options={
                'unique_together': {('booking', 'resource')},
            },
        ),
    ]
