# Generated by Django 4.2.30 on 2026-09-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learner",
            name="booking_for_someone_else",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="learner",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="learner",
            name="profile_photo_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="learner",
            name="student_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
