# Generated by Django 4.2.30 on 2026-08-28 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teachers", "0004_teacher_work_experience"),
        ("bookings", "0004_booking_learner_google_event_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("platform_fee", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "teacher_earnings",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("card", "Card"),
                            ("mtn_momo", "MTN Mobile Money"),
                            ("airtel_money", "Airtel Money"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "payout_status",
                    models.CharField(
                        choices=[
                            ("held", "Held by platform"),
                            ("paid_out", "Paid out to teacher"),
                        ],
                        default="held",
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(max_length=40, unique=True)),
                ("payer_label", models.CharField(blank=True, max_length=40)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("paid_out_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="bookings.booking",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments_received",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
